### ISSUE TITLE
How to deploy without using OBS and other screencasting and streaming app.

### ISSUE THREAD

**Issue by chimmykk** [livekit-examples/livestream#10]
Issue Description
Context
Guidance or updates on deploying and running a project/application without relying on OBS (Open Broadcaster Software) or any other screencasting/streaming applications. I am looking for alternative methods and approaches that can achieve the desired result without using such tools.

**Comment by davidzhao** [comment]
@chimmykk you can publish from any LiveKit SDK directly. Check out [publishing tracks](https://docs.livekit.io/realtime/client/publish/) for examples on how to achieve as such.
