### ISSUE TITLE
Live stream audio issues

### ISSUE THREAD

**Issue by PeRcHiK31** [livekit-examples/livestream#14]
Heyo, I didn't find any guide regarding issues, so I'll describe it as it is.

I'm experimenting with LiveKit and in particular with OBS to get a WebRTC/WHIP broadcast, I can push the signal, but using this project for tests I can't get sound regardless of whether I'm using WHIP or RTMP or whether there is sound in the scene itself or not. I would like to know and hope for help since I'm not familiar with the LiveKit code and SDK yet, is there a way to get audio on the broadcast, are there any bugs or maybe I should add or change something in the code to get it?

For more context, I tried to use both the self-hosted version and the cloud version and in both cases I have no sound.

Thank you in advance <3

**Comment by Furindo** [comment]
i'm having the same issue

**Comment by gravitynomad** [comment]
Same here

**Comment by cacheonly** [comment]
Apologies for the late response 🙏  We've added back a control that should address browser autoplay settings. If the browser requires user input before publishing audio, the user will need to click the video player to enable audio.
