### ISSUE TITLE
RTMP stream from OBS seems to be acknowledged, but never plays

### ISSUE THREAD

**Issue by smolgrrr** [livekit-examples/livestream#5]
Using normal OBS set up which works fine with any other rtmp server, but doesnt seem to work for livestream-demo.livekit.io or locally with my own key/subdomain.
On page load, it appears the stream is connected, but no content/audio is ever shown
<img width="817" alt="image" src="https://user-images.githubusercontent.com/104137257/232224080-d24f0c7a-6073-4a95-b3c9-adf89cb1c60c.png">
<img width="817" alt="image" src="https://user-images.githubusercontent.com/104137257/232224116-d4dc4716-b593-48ce-aa9d-118e2d7771eb.png">

**Comment by smolgrrr** [comment]
@cacheonly hey any ideas on what the issue might be?
are you using OBS?

**Comment by vidjul** [comment]
Hello, sorry for commenting on a closed issue.

I have the exact same issue. Has this been fixed?

~(cc @ smolgrrr)~ (sorry for the ping!)

**EDIT:** I've managed to fix the issue by removing the provided presets for the ingress and having only:
```
          video: {
            preset: IngressVideoEncodingPreset.H264_1080P_30FPS_3_LAYERS,
          },
```
